version: "3"
services:
  sqs:
    image: "softwaremill/elasticmq:latest"
    container_name: "queue"
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - "./docker/queue:/opt/custom"
    stdin_open: true
    tty: true
